language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - CRYPTOGRAPHY_VERSION=2.2.2 # Most recent version on pip
  - CRYPTOGRAPHY_VERSION=1.7.1 # Version in Debian 9's apt repositories

install:
  - pip install cryptography==$CRYPTOGRAPHY_VERSION
  - pip install pytest
  - pip install pynacl # This is required for the tests, not for the module itself
  - python setup.py install

script: py.test
